services:
  morana_worker:
    container_name: morana_worker_devcontainer
    build: .
    restart: "no"
    user: "morana"
    volumes:
      - ..:/workspace
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080