name: test

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-26.04

    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'

    - name: install dependencies
      run: npm ci

    - name: lib ts compile
      run: npm run tsc:lib
    - name: run lib linter
      run: npm run lint:lib
    - name: run lib tests
      run: npm run test:lib

    - name: example app ts compile
      run: npm run tsc:app
    - name: run example app linter
      run: npm run lint:app
